# Generated by Django 5.1.7 on 2025-03-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_category_movies_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=10, unique=True, verbose_name='分类'),
        ),
    ]
