# Generated by Django 5.1.7 on 2025-03-24 12:32

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='logo',
            field=models.ImageField(default='default.png', upload_to='', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='content',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Text'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category', to='index.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default='2002-3-11', verbose_name='上映时间'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='title',
            field=models.CharField(blank=True, default='', max_length=50, unique=True, verbose_name='电影名字'),
            preserve_default=False,
        ),
    ]
