# Generated by Django 5.1.7 on 2025-03-24 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_movies_logo_alter_content_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='头像'),
        ),
        migrations.RemoveField(
            model_name='movies',
            name='category',
        ),
        migrations.AlterField(
            model_name='movies',
            name='logo',
            field=models.ImageField(default='mv_default.png', upload_to='', verbose_name='封面'),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='', verbose_name='头像'),
        ),
        migrations.AddField(
            model_name='movies',
            name='category',
            field=models.ManyToManyField(default='未定义', related_name='category', to='index.category'),
        ),
    ]
