# Generated by Django 5.1.7 on 2025-03-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_actor_avatar_remove_movies_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movies',
            name='info',
            field=models.TextField(default='', verbose_name='电影简介'),
            preserve_default=False,
        ),
    ]
