# Generated by Django 5.1.7 on 2025-03-27 09:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_movies_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='timestamp'),
            preserve_default=False,
        ),
    ]
